import Head from "next/head"
import Image from "next/image"
 
import SignupForm from "../components/file-uploadform";

import { useFormik } from "formik"

export default function About() {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <SignupForm />
      </main>
    </div>
  )
}